name: Sync with S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          choco install awscli

      - name: Sync with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIATTSKFWFRYMGWRYVT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.acVHEJwgFAeacEfGGklSlcIXUgIcH7/4ClE29La4 }}
          AWS_DEFAULT_REGION: ${{ secrets.us-east-1 }}  # Use the secret for the region
        run: |
          aws s3 sync . s3://${{ secrets.jgfinalprojectbucket }}/ --delete
