name: Sync with S3

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' instead of 'windows-latest' for AWS CLI

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

           - name: Install AWS CLI
        run: |
          aws --version || (curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install --update)
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Sync with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Update to your AWS region
        run: |
          aws s3 sync . s3://jgfinalprojectbucket/ --delete
