name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AKIATTSKFWFRXBKD2O7K }}
          aws-secret-access-key: ${{ secrets.kEOyNyxoLyJwuRmk/nGXEzKx/mb61eFUY/ACQZEs }}
          aws-region: ${{ secrets.us-east-1 }}

      - name: Sync files to S3
        run: aws s3 sync . s3://${{ secrets.jgfinalprojectbucket }}/ --delete

