name: Sync with S3

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync with S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIATTSKFWFRXBKD2O7K }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.kEOyNyxoLyJwuRmk/nGXEzKx/mb61eFUY/ACQZEs }}
          AWS_DEFAULT_REGION: ${{ secrets.us-east-1 }}
        run: |
          aws s3 sync . s3://${{ secrets.jgfinalprojectbucket }}/ --delete
